### ISSUE TITLE
CGNS failing due to > 1.8 HDF5 library version being used with older CGNS versions to generate files.

### ISSUE THREAD

**Issue by brtnfld** [CGNS/CGNS#702]
cgnsupdate, cgnsview etc. can have issues with older CGNS files generated with > 1.8 HDF5 file formats. 

For example, CGNS 3.3 used the latest library format of HDF5 by default, but CGNS 4.4 forces HDF5 compatibility to 1.8. So  CGNS 3.3 compiled with HDF5 1.10 has a file format that would be HDF 1.10, but 4.4 will try to set the HDF5 version to 1.8 by default, which will fail since HDF5 can’t downgrade a newer HDF5 format to an older HDF5 format. So we must allow the format to match the one given in that case.

**Comment by MicK7** [comment]
I think that the issue is more that we try to open the file in modify mode. In read only mode there is no issue.

Thus a modification to have a "skip/don't care about compatibility" option when opening the file for those applications would be needed. It needs to be an user choice because it will lead to CGNS files not compatible with other implementation of CGNS or break backward compatibility.

**Comment by brtnfld** [comment]
But for the cgnsupdate, there is no way to create a CGNS 4.4 for a CGNS 3.3 file that used an HDF5 library > 1.8. Further, opening/modifying a 3.3 > 1.8 HDF5 with CGNS will probably fail when it tries to set libverbounds latest to be 1.8. I need to test this to verify. The user does not have a choice; an HDF5 1.14 file can not be made compatible with an HDF5 1.8 file format.

**Comment by brtnfld** [comment]
I have looked more into this. The CGNS file I have was created with HDF5 1.10 libvers file format  (which is possible as the older CGNS versions set the HDF5 library to the latest, and the CGNS library was compiled with HDF5 1.10). Currently, CGNS will set the fapl for opening the file to the use latest 1.8 file format, but when H5Fopen is called to open a  1.10 HDF5 format file with that fapl, the open call will fail since this condition can not be met.

**Comment by TonyGarratt** [comment]
Thanks for looking into this. This explains it.

So you are saying the latest CGNS version - 4.4 - forces you to use HDF1.8? Or at least can only open older CGNS files that uses HDF5 versions <=1.8?

I can understand that if someone built CGNS version x against version HDF5 a and then build of CGNS y>x must be built against HDF b>=a, but it does not make sense to me that a given CGNS version forces the user to build against a specific CGNS version 1.8.

I am probably second guessing this Scot. Can you confirm exactly that the rule is please for CGNS versions built against HDF version.  Are you saying that to open an old CGNS file it must have been built with HDF5 no greater than 1.8?

Thanks
Tony
________________________________

**Comment by brtnfld** [comment]
Some older CGNS versions are always set to use the latest format, so if you are using HDF5 1.10, then the format will be HDF5 1.10. But the latest CGNS version, 4.3, always assumes that the format is HDF5 1.8 hence the error. 

This change allows for opening and writing to that CGNS file. However, after the completion, it will still be in HDF5 1.10 file format. Being that it is an HDF5 1.10 file, it will not be able to be read by a CGNS version built with HDF 1.8. A user would have to run h5repack to downgrade it to 1.8 HDF5.

It is not the case that CGNS needs to be built for a specific version of 1.8. CGNS can be built with any version of HDF5; the particular case is if it was built with HDF5 1.8 and comes across a file in a newer format, CGNS versions < 4.4 will not be able to open it.

**Comment by TonyGarratt** [comment]
Thanks Scot - this makes sense now.

The change made in 4.3 - i.e. assuming the format is HDF 1.8 - was done to allow an older CGNS file to opened in modify mode and written too. That makes sense to me.

I did not know about h5repack - that is a useful tool we can use in these circumstances.

OK - I am happy with this rule now that I understand it. The defect can be closed.

So.... this brings up back to the release of 4.4. Is that still planned for May? I guess not since it's the last day of May today! Do you have a new date? I am asking because Ansys is going to move from 4.3 to 4.4 for the next Ansys release we are working on so our build team is keen to get the official 4.4 source code and start building it for the various consumers within Ansys.

Many Thanks
Tony
________________________________

**Comment by brtnfld** [comment]
Fixed

**Comment by brtnfld** [comment]
@TonyGarratt, do you have a target date in mind? I would like to complete the multi-dataset feature, but I can release what we have if necessary.

**Comment by TonyGarratt** [comment]
Let me ask our build teams and Ill get back to you with a target date.

Thanks
Tony
________________________________

**Comment by TonyGarratt** [comment]
The sooner the better for the our next release - because we have to build the various versions that each product uses and then each product has to consume the new build and do regression testing.

However, having said that, we could wait a few weeks if that is enough time for you to finish the multi-dataset feature.

To be very specific if it was released by the end of next week - June 9th - that would still work for us because it is early enough in our first development iteration of our next release to give us enough time to get it built and made available for consumption during our first iteration.

Does that help?

Thanks
Tony
________________________________

**Comment by brtnfld** [comment]
@TonyGarratt, I'm done with the feature and have a PR for it. The only uncertainty is Windows CI testing. We don't test OneAPI with HPC tool kit for Windows (i.e. parallel). Are you testing it with that configuration that you could try the branch before it goes into develop?

**Comment by TonyGarratt** [comment]
We use CGNS parallel on Windows. We are using Intel compilers C++ and Fortran on Windows - but the "legacy" oneAPI versions - i.e. not the new LLVM based versions. I can get and test the branch on Windows in parallel - is that sufficient to cover what you would like to test - i.e. parallel CGNS on Windows?

Thanks
Tony
________________________________

**Comment by TonyGarratt** [comment]
We are currently using  HDF5 1.12.2 . Getting our build team to use 1.14 is going to create some extra work for them which will be hard for me to justify.

But you will still get some good testing of CGNS parallel on Windows nevertheless.

Hope that is OK.

Thanks
Tony
________________________________
